config/routes.rb
FeVrn::Application.routes.draw do

  post "feedback", to: 'feedback#create', as: 'feedback_create'
  get "pages/show"

  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'main#index'

  resources :categories, only: :show do
    resources :products, only: :show
  end

  namespace :cart do
    post 'items/:id', to: "items#create", as: 'items'
  end

  get 'cart' => 'cart#index', as: 'cart_index'
  put 'cart' => 'cart#update', as: 'cart'

  resources :orders, only: [:new, :create]
  resources :articles, :pages, only: :show
  resources :yandex_market, :sitemap, :contacts, only: :index

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    cannot :destroy, Order
    cannot :destroy, Order::Item
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_ancestry
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  validates :title, presence: true
  default_scope -> { order(:position) }
end

app/models/cart.rb
class Cart

  attr_reader :items

  def initialize
    @items = []
  end

  def add(product_id, quantity=1)
    current_item = self.item(product_id)
    if current_item
      current_item.increment_quantity(quantity)
    else
      @items << Cart::Item.new(product_id, quantity)
    end
  end

  def price
    @items.sum{ |item| item.price }
  end

  def quantity
    @items.sum{ |item| item.quantity }
  end

  def empty?
    @items.size <= 0
  end

  def empty!
    @items.delete_if { |i| true }
  end

  def delete_item(id)
    @items.delete_if { |item| item.product_id == id.to_i }
  end

  def delete_by_id(product_id)
    @items.delete_if { |i| !!Product.find(i.product_id) }
  end

  def delete_broken_items
    @items.delete_if { |i| ! !!Product.find(i.product_id) }
  end

  def item(id)
    @items.find { |item| item.product.id == id }
  end

  def to_s
    datas = []
    items.each { |item| datas << item.to_s }
    datas << "Итого: #{price} руб."
    datas
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_ancestry
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  validates :name, presence: true
  default_scope -> { order(:position) }
  has_many :products, dependent: :destroy

  class << self
    def for_category(cat)
      includes(:products).find(cat)
    end
  end

end

app/models/firm.rb
class Firm < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_reader :name
  validates :first_name, :last_name, :phone, :address, presence: true

  has_many :items, dependent: :destroy

  state_machine :state, initial: :initialized do
    
    state :initialized, :inprogress, :finished

    event :finish do
      transition all => :finished
    end

  end
  
  def state_enum
    [[ 'Новый заказ', 'initialized'], ['В работе', 'inprogress'], ['Завершен', 'finished']] 
  end

  def name
    self.class.model_name.human + " #" + id.to_s
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  has_ancestry
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  validates :title, presence: true
  validates :key, uniqueness: true
  default_scope -> { order(:position) }
  scope :for_menu, -> { where(show_in_menu: true) }
  DEF_EXCLUDEDS = %w(contacts)

  class << self
    
    def contacts
      where(key: 'contacts').first
    end
    
    def with_key(key)
      where(key: key.to_s).first
    end

    def without_excluded(excluded = [])
      where('key NOT IN (?)', DEF_EXCLUDEDS)
    end

  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :image, presence: true
  has_ancestry
  mount_uploader :image, PhotoUploader
  belongs_to :product

  default_scope -> { order('created_at') }

#  def id #TODO починить это говно. Без этого не работает edit в админке у товара
#    super.to_s
#  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :price, :category_id, presence: true
  validates :lot, uniqueness: true, allow_blank: true
  has_ancestry
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  serialize :related_products, Array
  has_many :photos, dependent: :destroy
  belongs_to :category
  has_one :yandex_market_info
  accepts_nested_attributes_for :yandex_market_info, :photos, allow_destroy: true
  
  default_scope -> { where(disabled: false).order('category_id, price, name') }
  scope :main_page, -> { where(show_on_main_page: true) }

  def yandex_market_ready?
    if y_m = self.yandex_market_info
      y_m.firm_id && !y_m.model.empty? && self.price > 0
    end
  end
  
  def related_products_enum
    Product.order(:name).map { |p| [p.name, p.id] }
  end

  def related
    self.class.includes(:category).find(self[:related_products][1..-1])
  end

  def has_related?
    related.size > 0
  end

  def photos_count
    photos.count
  end

  def main_photo
    photos.first.try(:image) || false
  end

  def photos?
    photos.size > 0
  end

  def more_photos?
    photos.size > 1
  end

  def more_photos
    photos[1..-1]
  end

  def destroy
    update_attributes(disabled: true)
  end
  alias destroy! destroy

end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, presence: true
  has_and_belongs_to_many :users
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  has_ancestry
  mount_uploader :image, SlideUploader
  default_scope -> { order(:position) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  def role?(role)
    !!self.roles.find_by_name(role.to_s.downcase)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= seo_content(:title)
    %meta{ content: 'text/html; charset=UTF-8', :'http-equiv' => 'Content-Type' }
    %meta{ name: 'keywords', content: seo_content(:keywords) }
    %meta{ name: 'description', content: 'Магазин по продаже солнечных батарей, солнечных панелей в Воронеже' }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    %link{ rel: 'shortcut icon', href: image_path('favicon.ico'), type: 'image/x-icon' }
    = csrf_meta_tags
  %body
    = gflash
    .container
      .raw
        .navbar
          .navbar-inner
            = link_to image_tag('logo.png'), root_path, id: 'logo', alt: 'free energy'
            #slogans_block
              .first Свободная энергия
              .second Free energy
            #contacts_block
              .phone
                %span.prefix +7 (903)
                %span.number 656-91-33
              .phone
                %span.prefix +7 (906)
                %span.number 680-33-30
              .address г.Воронеж, ТЦ "Европа", 3 этаж, магазин "Землянка"
      .raw
        = render partial: 'shared/carousel', locals: { slides: @slides }
      .raw
        .span3
          = render '/shared/side_menu'
          #cart
            %h4 Ваша корзина: 
            = render partial: 'shared/cart_content', locals: { cart: @cart }
        .span1
        .span8
          = notice
          = alert
          #content= yield
      .clearfix
      #footer.raw
        = link_to 'Разработка и продвижение сайта - NikSan', 'http://niksan.ru', target: '_blank'
    = render 'shared/yandex_metrica'
    = render 'shared/google_analitics'

app/views/shared/_carousel.html.haml
- if slides.size > 1
  #myCarousel.carousel.slide
    .carousel-inner
      - slides.try(:each) do |slide|
        - if slide == slides.first
          .item.active= image_tag slide.image.medium.url, alt: slide.alt
        - else
          .item= image_tag slide.image.medium.url, alt: slide.alt
          
    = link_to raw('&lsaquo;'), '#myCarousel', :'data-slide' => 'prev', class: 'carousel-control left'
    = link_to raw('&rsaquo;'), '#myCarousel', :'data-slide' => 'next', class: 'carousel-control right'

app/views/shared/_cart_content.html.haml
#cart_content
  - if !@cart.empty?
    %p
      = cart.quantity
      = t('cart.products')
    %p
      = t('cart.on_sum')
      = cart.price
      = t('cart.currency')
    = link_to t('cart.go_to_cart'), cart_index_path, class: 'btn btn-success', id: "to_cart_index"
  - else
    %p= t('cart.empty') 

app/views/shared/_google_analitics.html.erb
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48292272-1', 'fe-vrn.ru');
  ga('send', 'pageview');
</script>

app/views/shared/_side_menu.html.haml
%ul.nav.nav-list.well
  - @pages.each do |page|
    %li= link_to page.title, page_path(page)
  .divider
  %li.nav-header Категории
  - @root_categories.each do |cat|
    %li= link_to cat.name, category_path(cat)
  .divider
  %li.nav-header Статьи
  - @articles.each do |article|
    %li= link_to article.title, article_path(article)

app/views/shared/_yandex_metrica.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter23651068 = new Ya.Metrika({id:23651068,
                    webvisor:true,
                    clickmap:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/23651068" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->